### ISSUE TITLE
I look forward to your tutorial.

### ISSUE THREAD

**Issue by TheYMing** [kleinicke/fast_web_style_transfer#1]
I look forward to your tutorial. I have tried using your program. The effect is very good. No matter there are some minor problems, for example, there are only two styles, and then you need to re-upload pictures every time the style is transferred.

**Comment by kleinicke** [comment]
Hey, thank you for using it.
Yeah I'm about to further improve the site. The problem is, that higher resolutions don't work very well. I could add new styles easily, since they only train for 5 hours on google colab.
I implemented it using onnx.js, but I don't think that this framework has a big future. It seems like Microsoft lost the interest in the framework.

**Comment by kleinicke** [comment]
A first version of the tutorial is now life.
Feel free to provide feedback.
I'll have to erase a few more typos, create subpages and improve my css.
